services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000" # Exponer el puerto 8000 para la API de ChromaDB
    volumes:
      - chromadb_data:/data # Persistencia de datos

  streamlit_app:
    build: .
    ports:
      - "8501:8501"  # Mapea el puerto 8501 del contenedor al host
    volumes:
      - .:/app       # Monta el directorio actual en /app dentro del contenedor
    depends_on:
      - chromadb     # Asegura que ChromaDB se inicie antes que Streamlit
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ENABLECORS=false

volumes:
  chromadb_data: